version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      day: friday
      time: '04:00'
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
  - package-ecosystem: terraform
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
      day: friday
      time: '04:30'
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
