pull_request_rules:
  - name: automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
    actions:
      squash:
        commit_message: title+body
      rebase:
      merge:
        method: rebase
      delete_head_branch:
