repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^.*/\.infracost/terraform_modules/manifest\.json$
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-yaml
      - id: detect-aws-credentials
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      #
      # NOTE: this is very slow you might want to enable it
      # from time to time but not on every commit
      # - id: terraform_providers_lock
      #   args:
      #     - --tf-init-args=-upgrade
      #     - --args=-platform=windows_amd64
      #     - --args=-platform=darwin_amd64
      #     - --args=-platform=darwin_arm64
      #     - --args=-platform=linux_amd64
      - id: terraform_validate
      - id: tfupdate
        name: Autoupdate Terraform versions
        args:
          - --args=terraform --version "~> 1.3"
      - id: tfupdate
        name: Autoupdate aws provider versions
        args:
          - --args=provider aws --version ">= 4.30.0, < 5.0.0"
      - id: tfupdate
        name: Autoupdate helm provider versions
        args:
          - --args=provider helm --version ">= 2.8.0, < 3.0.0"
      - id: tfupdate
        name: Autoupdate pass provider versions
        args:
          - --args=provider mecodia/pass --version ">= 3.1.0, < 4.0.0"
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - "--args=--lockfile=false"
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        args:
          - "--args=--module"
          - "--args=--config=.tflint.hcl"
      - id: terraform_tfsec
      - id: terraform_checkov
        args:
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml
