output "name" {
  description = "The name of the helm release"
  value       = data.helm_template.main.name
}

output "namespace" {
  description = "The namespace of the helm release"
  value       = data.helm_template.main.namespace
}

output "manifest" {
  description = "Rendered Kubernetes manifests generated by Helm"
  sensitive   = true
  value       = data.helm_template.main.manifest
}
