name: Pull Request Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:

  pull-request-labeler:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
